SELECT [T].[DeviceID] AS [DeviceId]
    ,[T].[FactoryID] AS [FactoryId]
    ,System.TimeStamp AS [Tst]
    ,UDF.ParseDateTime([T].[DeviceTime]) AS [DeviceTime]
    ,[T].[DeviceStatus] AS [DeviceStatus]
    ,UDF.ParseDateTime([T].[MachineTime]) AS [MachineTime]
    ,[T].[MachineState] AS [MachineState]
    ,UDF.DayTimeToSec([T].[RunTime]) AS [RunTime]
    ,DATEDIFF(second, '00:00:00', CAST(System.TimeStamp AS DATETIME)) - [__DeviceCNC__].[ShiftStartTimeSec] AS [ShiftTime]
    ,CAST([T].[SpindleLoad] as float) AS [SpindleLoad]
    ,CAST([T].[XAxisLoad] as float) AS [XAxisLoad]
    ,CAST([T].[YAxisLoad] as float) AS [YAxisLoad]
    ,CAST([T].[ZAxisLoad] as float) AS [ZAxisLoad]
    ,CAST([T].[SpindlePtc] as float) AS [SpindlePtc]
    ,CAST([T].[FeedPtc] as float) AS [FeedPtc]
    ,CAST([T].[TraversePtc] as float) AS [TraversePtc]
INTO
    [__TelemetryCNC__]
FROM
    [__IoTHub__] [T]
    INNER JOIN [__Device__] ON [T].[DeviceID] = [__Device__].[DeviceID]
    INNER JOIN [__DeviceCNC__] ON [__Device__].[Id] = [__DeviceCNC__].[Device]
